services:
  caddy:
    image: caddy
    # image: picobug/franken
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.caddy.rule=HostRegexp(`^([a-z]+\.)?(${DOMAIN_MAIN}|${DOMAIN_EXT})\.(${EXT_DOMAIN})$`)'
      - 'traefik.http.routers.caddy.entrypoints=websecure'
      - 'traefik.http.routers.caddy.tls=true'
      - 'traefik.http.routers.caddy.service=caddy'
      - 'traefik.http.routers.caddy.middlewares=caddy'
      - 'traefik.http.middlewares.caddy.compress=true'
      - 'traefik.http.services.caddy.loadbalancer.server.port=80'
    restart: unless-stopped
    volumes:
      - ./caddy:/etc/caddy
      - ../www:/www
    depends_on:
      - phpdev
      - php
  nginx:
    image: nginx:alpine
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.slim.rule=HostRegexp(`^([a-z]+\.)?(${DOMAIN_MAIN})\.(${EXT_DOMAIN})$`)'
      - 'traefik.http.routers.slim.entrypoints=websecure'
      - 'traefik.http.routers.slim.tls=true'
      - 'traefik.http.routers.slim.service=slim'
      - 'traefik.http.routers.slim.middlewares=slim'
      - 'traefik.http.middlewares.slim.compress=true'
      - 'traefik.http.services.slim.loadbalancer.server.port=80'
    volumes:
      - ../www:/www
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/base/:/etc/nginx/base/
      - ./nginx/site.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - php
      - phpdev
    env_file:
      - .env
    restart: always

  ### PHP-FPM Container #######################################

  php:
    hostname: "${PHP_HOST}"
    image: picobug/php:7
    user: www-data
    volumes:
      - ../www:/www
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
      - postgres
      - redis
    restart: always

  phpdev:
    hostname: "${PHP_DEV_HOST}"
    image: picobug/php:node
    user: www-data
    volumes:
      - ../www:/www
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
    restart: always

  ### Redis Container #######################################

  redis:
    image: rapidfort/redis:7.2
    ulimits:
      memlock: -1
    hostname: "${DB_HOST}"
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.redis.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.redis.entrypoints=redis'
      - 'traefik.tcp.routers.redis.service=redis-proxy'
      - 'traefik.tcp.services.redis-proxy.loadbalancer.server.port=6379'
    volumes:
      - redis:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: 'pico404'
      REDIS_EXTRA_FLAGS: '--maxmemory 256mb --appendonly no --maxmemory-policy allkeys-lru'
    restart: always
  
  ### MariaDB Container #######################################

  mariadb:
    #image: mariadb:lts
    image: rapidfort/mariadb-official:11.4.2-noble
    hostname: "${DB_HOST}"
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.mariadb.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.mariadb.entrypoints=mariadb'
      - 'traefik.tcp.routers.mariadb.service=mariadb-proxy'
      - 'traefik.tcp.services.mariadb-proxy.loadbalancer.server.port=3306'
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: julio_pico
      MARIADB_USER: julio
      MARIADB_PASSWORD: "${USER_PASS}"
      MARIADB_ROOT_PASSWORD: "${ROOT_PASS}"
      MARIADB_AUTO_UPGRADE: true
    restart: always

  ### PostgreSQL Container ####################################

  postgres:
    image: postgres:alpine
    #image: rapidfort/postgresql-official:16.3-bookworm
    hostname: "${DB_HOST}"
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.routers.postgres.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.postgres.entrypoints=postgres'
      - 'traefik.tcp.routers.postgres.service=postgres-proxy'
      - 'traefik.tcp.services.postgres-proxy.loadbalancer.server.port=5432'
    volumes:
      #- keydb:/var/lib/postgresql/data
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: julio_pico
      POSTGRES_USER: julio
      POSTGRES_PASSWORD: "${USER_PASS}"
    restart: always
volumes:
  mariadb:
    driver: 'local'
  redis:
    driver: 'local'
  postgres:
    driver: 'local'
  keydb:
    driver: 'local'

networks:
  default:
    external: true
    name: picobug
