version: '3.3'

services:

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/base/:/etc/nginx/base/
            - ./nginx/site.conf:/etc/nginx/nginx.conf
        links:
            - php7:php-fpm
            # - node
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.100

### PHP-FPM Container #######################################

    php7:
        build:
            context: ./php7
        volumes:
            - ./www:/www
            - ./php7/www.conf:/etc/php7/php-fpm.d/www.conf
        links:
            - "mariadb:mdb"
            - "postgres:pdb"
            - vsftpd
            - redis
        extra_hosts:
            - "keepo.dev:172.16.1.100"
            - "m.keepo.dev:172.16.1.100"
            - "media.keepo.dev:172.16.1.100"
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.200

### VSFTPD Container #######################################
            
    vsftpd:
        build:
            context: ./vsftpd
        ports:
        - "21:21"
        - "21100-21110:21100-21110"
        volumes:
            - ./www/sites/media.keepo:/home/julio
        environment:
            FTP_USER: julio
            FTP_PASS: pico
            PASV_ADDRESS: 172.16.1.201
            PASV_MIN: 21100
            PASV_MAX: 21110
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.201

### Redis Container #######################################
    
    redis:
        build:
            context: ./redis
        volumes:
            - redis:/data
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.202

### Nodes Container #######################################
    
    nodes:
        build:
            context: ./nodes
        ports:
            - "9001:8080"
        networks:
            default:
                ipv4_address: 172.16.1.101

### MariaDB Container #######################################

    mariadb:
        build: ./mariadb
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: julio_pico
            MYSQL_USER: julio
            MYSQL_PASSWORD: pico
            MYSQL_ROOT_PASSWORD: root
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.210

### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: julio
            POSTGRES_USER: julio
            POSTGRES_PASSWORD: pico
        restart: always
        networks:
            default:
                ipv4_address: 172.16.1.211

volumes:
  mariadb:
    driver: "local"
  redis:
    driver: "local"
  postgres:
    driver: "local"

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.1.0/24
