version: '3.3'

services:
  nginx:
    image: nginx:alpine
    labels:
      - 'traefik.http.routers.slim.rule=HostRegexp(`${DOMAIN_EXT}`,`${DOMAIN_MAIN}`,`{subdomain:[a-z]+}.${DOMAIN_MAIN}`)'
      - 'traefik.http.routers.slim.entrypoints=websecure'
      - 'traefik.http.routers.slim.tls=true'
      - 'traefik.http.routers.slim.service=slim'
      - 'traefik.http.services.slim.loadbalancer.server.port=80'
    volumes:
      - ../www:/www
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/base/:/etc/nginx/base/
      - ./nginx/site.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - php
    env_file:
      - .env
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.100

  ### PHP-FPM Container #######################################

  php:
    hostname: "${PHP_HOST}"
    image: picobug/php:7
    user: www-data
    volumes:
      - ../www:/www
      - ./php/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
      - postgres
      - redis
    restart: always
    extra_hosts:
      - "${DOMAIN_MAIN}:172.16.1.100"

  ### Redis Container #######################################

  redis:
    image: redis:alpine
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.redis.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.redis.entrypoints=redis'
      - 'traefik.tcp.routers.redis.service=redis-proxy'
      - 'traefik.tcp.services.redis-proxy.loadbalancer.server.port=6379'
    volumes:
      - redis:/data
    command: redis-server --maxmemory 64mb --appendonly no --maxmemory-policy allkeys-lfu
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.202

  ### MariaDB Container #######################################

  mariadb:
    image: mariadb
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.mariadb.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.mariadb.entrypoints=mariadb'
      - 'traefik.tcp.routers.redis.service=mariadb-proxy'
      - 'traefik.tcp.services.mariadb-proxy.loadbalancer.server.port=3306'
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: julio_pico
      MYSQL_USER: julio
      MYSQL_PASSWORD: pico
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      MYSQL_INITDB_SKIP_TZINFO:
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.210

  ### PostgreSQL Container ####################################

  postgres:
    image: postgres:alpine
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.postgres.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.postgres.entrypoints=postgres'
      - 'traefik.tcp.routers.redis.service=postgres-proxy'
      - 'traefik.tcp.services.postgres-proxy.loadbalancer.server.port=5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - './postgres:/docker-entrypoint-initdb.d'
      - './logs:/docker-entrypoint-preinitdb.d'
    environment:
      POSTGRES_DB: julio_pico
      POSTGRES_USER: julio
      POSTGRES_PASSWORD: pico
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.211

volumes:
  mariadb:
    driver: 'local'
  redis:
    driver: 'local'
  postgres:
    driver: 'local'

networks:
  default:
    external: true
    name: picobug
