version: '3.3'

services:
  ### PPM PHP Server Balancer
  ppm:
    image: phppm/nginx
    command: --debug=1 --app-env=dev --bootstrap=laravel --static-directory=public/
    volumes:
      - ../www/sites/picobug:/var/www
    extra_hosts:
      - 'keepo.loc:172.16.1.100'
      - 'm.keepo.loc:172.16.1.100'
      - 'media.keepo.loc:172.16.1.100'
      - 'picobug.loc:172.16.1.100'
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.101

  ### Nginx Server Container ##################################

  nginx:
    image: fholzer/nginx-brotli
    volumes:
      - ../www:/www
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ~/.local/certs/:/etc/nginx/cert/
      - ./nginx/base/:/etc/nginx/base/
      - ./nginx/site.conf:/etc/nginx/nginx.conf
    depends_on:
      # - phpv8
      - php7
      # - node
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.100

  ### PHP-FPM Container #######################################

  php7:
    image: picobug/php7
    volumes:
      - ../www:/www
      - ./php/alpine/www.conf:/etc/php7/php-fpm.d/www.conf
    depends_on:
      - mariadb
      - postgres
      - redis
    restart: always
    extra_hosts:
      - 'keepo.loc:172.16.1.100'
      - 'm.keepo.loc:172.16.1.100'
      - 'media.keepo.loc:172.16.1.100'

  ### PHP-FPM Container #######################################

  phpv8:
    image: alexmasterov/alpine-php:7.1
    volumes:
      - ../www:/www
      - ./php/alpinev8js/php.conf:/etc/php/php-fpm.conf
      - ./php/alpinev8js/conf.d/ext71.ini:/etc/php/conf.d/ext.ini
    depends_on:
      - postgres
      - redis
    restart: always
    extra_hosts:
      - 'keepo.loc:172.16.1.100'
      - 'm.keepo.loc:172.16.1.100'
      - 'media.keepo.loc:172.16.1.100'
      - 'picobug.loc:172.16.1.100'

  ### VSFTPD Container #######################################

  vsftpd:
    image: picobug/ftp
    volumes:
      - ../www/sites/media.keepo:/home/julio
    environment:
      FTP_USER: julio
      FTP_PASS: pico
      PASV_ADDRESS: 172.16.1.201
      PASV_MIN: 21100
      PASV_MAX: 21110
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.201

  ### Redis Container #######################################

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    # command: redis-server --requirepass picoredis --maxmemory-policy allkeys-lru
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.202

  ### Nodes Container #######################################

  nodes:
    build:
      context: ./nodes

  ### MariaDB Container #######################################

  mariadb:
    image: bitnami/mariadb
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # - ./mariadb/conf.d:/etc/mysql/conf.d
      - ../www:/www
      - mariadb:/bitnami/mariadb
    environment:
      MARIADB_DATABASE: julio_pico
      MARIADB_USER: julio
      MARIADB_PASSWORD: pico
      MARIADB_ROOT_PASSWORD: root
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.210

  ### PostgreSQL Container ####################################

  postgres:
    image: bitnami/postgresql
    volumes:
      - postgres:/bitnami/postgresql
      - './postgres:/docker-entrypoint-initdb.d'
      - './logs:/docker-entrypoint-preinitdb.d'
    environment:
      POSTGRESQL_DATABASE: julio_pico
      POSTGRESQL_USERNAME: julio
      POSTGRESQL_PASSWORD: pico
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.211

volumes:
  mariadb:
    driver: 'local'
  redis:
    driver: 'local'
  postgres:
    driver: 'local'

networks:
  default:
    external:
      name: picobug
