version: '3.3'

services:
  caddy:
    labels:
      - 'traefik.http.routers.caddy.rule=HostRegexp(`${DOMAIN_EXT}`,`{subdomain:[a-z\-\_]+}.${DOMAIN_EXT}`)'
      - 'traefik.http.routers.caddy.entrypoints=websecure'
      - 'traefik.http.routers.caddy.tls=true'
      - 'traefik.http.routers.caddy.service=caddy'
      - 'traefik.http.routers.caddy.middlewares=caddy'
      - 'traefik.http.middlewares.caddy.compress=true'
      - 'traefik.http.services.caddy.loadbalancer.server.port=80'
    image: caddy
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../www:/www
    depends_on:
      - php
      - phpdev
  nginx:
    image: nginx:alpine
    labels:
      - 'traefik.http.routers.slim.rule=HostRegexp(`${DOMAIN_MAIN}`,`{subdomain:[a-z\-\_]+}.${DOMAIN_MAIN}`, `${DOMAIN_DEV_MAIN}`,`{subdomain:[a-z\-\_]+}.${DOMAIN_DEV_MAIN}`)'
      - 'traefik.http.routers.slim.entrypoints=websecure'
      - 'traefik.http.routers.slim.tls=true'
      - 'traefik.http.routers.slim.service=slim'
      - 'traefik.http.routers.slim.middlewares=slim'
      - 'traefik.http.middlewares.slim.compress=true'
      - 'traefik.http.services.slim.loadbalancer.server.port=80'
    volumes:
      - ../www:/www
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/base/:/etc/nginx/base/
      - ./nginx/site.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - php
      - phpdev
    env_file:
      - .env
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.100

  ### PHP-FPM Container #######################################

  php:
    hostname: "${PHP_HOST}"
    image: picobug/php:7
    user: www-data
    volumes:
      - ../www:/www
      - ./php/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
      - postgres
      - redis
    restart: always
    extra_hosts:
      - "${DOMAIN_MAIN}:172.16.1.100"
      - "projek.pico.dev:172.16.1.100"

  phpdev:
    hostname: "${PHP_DEV_HOST}"
    image: picobug/php
    user: www-data
    volumes:
      - ../www:/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
      - postgres
      - redis
    restart: always
    extra_hosts:
      - "${DOMAIN_MAIN}:172.16.1.100"
    
  php80:
    image: picobug/php:80
    user: www-data
    volumes:
      - ../www:/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
      - postgres
      - redis
    restart: always
    extra_hosts:
      - "${DOMAIN_MAIN}:172.16.1.100"
      - "projek.pico.dev:172.16.1.100"
  
  php81:
    image: picobug/php:81
    user: www-data
    volumes:
      - ../www:/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
      - postgres
      - redis
    restart: always
    extra_hosts:
      - "${DOMAIN_MAIN}:172.16.1.100"
      - "projek.pico.dev:172.16.1.100"

  ### Redis Container #######################################

  redis:
    # image: eqalpha/keydb:alpine
    image: redis:alpine
    # image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.redis.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.redis.entrypoints=redis'
      - 'traefik.tcp.routers.redis.service=redis-proxy'
      - 'traefik.tcp.services.redis-proxy.loadbalancer.server.port=6379'
    volumes:
      - redis:/data
    # command: redis-server --appendonly no --maxmemory-policy allkeys-lfu
    command: redis-server --maxmemory 32mb --appendonly no --maxmemory-policy allkeys-lru
    # command: keydb-server /etc/keydb/keydb.conf --maxmemory 64mb --appendonly no --maxmemory-policy allkeys-lfu
    restart: always
  
  ### MariaDB Container #######################################

  mariadb:
    image: yobasystems/alpine-mariadb
    # image: jbergstroem/mariadb-alpine
    # image: mariadb
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.mariadb.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.mariadb.entrypoints=mariadb'
      - 'traefik.tcp.routers.mariadb.service=mariadb-proxy'
      - 'traefik.tcp.services.mariadb-proxy.loadbalancer.server.port=3306'
    # command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: julio_pico
      MYSQL_USER: julio
      MYSQL_PASSWORD: pico
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      MYSQL_INITDB_SKIP_TZINFO:
    restart: always

  ### PostgreSQL Container ####################################

  postgres:
    image: postgres:alpine
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.postgres.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.postgres.entrypoints=postgres'
      - 'traefik.tcp.routers.postgres.service=postgres-proxy'
      - 'traefik.tcp.services.postgres-proxy.loadbalancer.server.port=5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - './postgres:/docker-entrypoint-initdb.d'
      - './logs:/docker-entrypoint-preinitdb.d'
    environment:
      POSTGRES_DB: julio_pico
      POSTGRES_USER: julio
      POSTGRES_PASSWORD: pico
    restart: always
volumes:
  mariadb:
    driver: 'local'
  redis:
    driver: 'local'
  postgres:
    driver: 'local'
  keydb:
    driver: 'local'

networks:
  default:
    external: true
    name: picobug
