version: '3.3'

services:
  ### PPM PHP Server Balancer
  ppm:
    image: phppm/nginx
    command: --debug=1 --app-env=dev --bootstrap=laravel --static-directory=public/
    volumes:
      - ../www/sites/picobug:/var/www
    extra_hosts:
      - 'picobug.loc:172.16.1.100'
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.101

  ### Nginx Server Container ##################################

  nginx:
    image: nginx:alpine
    labels:
      - 'traefik.http.routers.slim.rule=HostRegexp(`local.loc`,`pico.loc`,`{subdomain:[a-z]+}.pico.loc`)'
      - 'traefik.http.routers.slim.entrypoints=websecure'
      - 'traefik.http.routers.slim.tls=true'
      - 'traefik.http.routers.slim.service=slim'
      - 'traefik.http.services.slim.loadbalancer.server.port=80'
    volumes:
      - ../www:/www
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ~/.local/certs/:/etc/nginx/cert/
      - ./nginx/base/:/etc/nginx/base/
      - ./nginx/site.conf:/etc/nginx/nginx.conf
    depends_on:
      # - phpv8
      - php
      # - node
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.100

  ### PHP-FPM Container #######################################

  php:
    hostname: slim_php
    image: picobug/php:mssql
    volumes:
      - ../www:/www
      - ./php/alpine/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
      #- ./php/alpine/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
    depends_on:
      - mariadb
      - postgres
      - redis
      # - mssql
    restart: always
    extra_hosts:
      - 'pico.loc:172.16.1.100'

  ### PHP-FPM Container #######################################

  phpv8:
    image: alexmasterov/alpine-php:7.1
    volumes:
      - ../www:/www
      - ./php/alpinev8js/php.conf:/etc/php/php-fpm.conf
      - ./php/alpinev8js/conf.d/ext71.ini:/etc/php/conf.d/ext.ini
    depends_on:
      - postgres
      - redis
    restart: always
    extra_hosts:
      - 'keepo.loc:172.16.1.100'
      - 'm.keepo.loc:172.16.1.100'
      - 'media.keepo.loc:172.16.1.100'
      - 'picobug.loc:172.16.1.100'

  ### VSFTPD Container #######################################

  vsftpd:
    image: picobug/ftp
    volumes:
      - ../www/sites/media.keepo:/home/julio
    environment:
      FTP_USER: julio
      FTP_PASS: pico
      PASV_ADDRESS: 172.16.1.201
      PASV_MIN: 21100
      PASV_MAX: 21110
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.201

  ### Redis Container #######################################

  redis:
    image: redis:alpine
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.redis.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.redis.entrypoints=redis'
      - 'traefik.tcp.routers.redis.service=redis-proxy'
      - 'traefik.tcp.services.redis-proxy.loadbalancer.server.port=6379'
    volumes:
      - redis:/data
    command: redis-server --maxmemory 64mb --appendonly no --maxmemory-policy allkeys-lfu
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.202

  ### Nodes Container #######################################

  nodes:
    build:
      context: ./nodes

  ### MariaDB Container #######################################

  mariadb:
    image: mariadb
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.mariadb.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.mariadb.entrypoints=mariadb'
      - 'traefik.tcp.routers.redis.service=mariadb-proxy'
      - 'traefik.tcp.services.mariadb-proxy.loadbalancer.server.port=3306'
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # - ./mariadb/conf.d:/etc/mysql/conf.d
      # - ./mariadb/conf.d/my.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
      # - mariadb:/bitnami/mariadb
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: julio_pico
      MYSQL_USER: julio
      MYSQL_PASSWORD: pico
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      MYSQL_INITDB_SKIP_TZINFO:
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.210

  ### PostgreSQL Container ####################################

  postgres:
    # image: bitnami/postgresql
    image: postgres:alpine
    hostname: db.pico.test
    labels:
      - 'traefik.tcp.routers.postgres.rule=HostSNI(`*`)'
      - 'traefik.tcp.routers.postgres.entrypoints=postgres'
      - 'traefik.tcp.routers.redis.service=postgres-proxy'
      - 'traefik.tcp.services.postgres-proxy.loadbalancer.server.port=5432'
    volumes:
      # - postgres:/bitnami/postgresql
      - postgres:/var/lib/postgresql/data
      - './postgres:/docker-entrypoint-initdb.d'
      - './logs:/docker-entrypoint-preinitdb.d'
    environment:
      POSTGRES_DB: julio_pico
      POSTGRES_USER: julio
      POSTGRES_PASSWORD: pico
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.211

  ### MSSQL Container #######################################

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: db.pico.test
    volumes:
      # - ./mariadb/conf.d:/etc/mysql/conf.d
      # - ./mariadb/conf.d/my.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
      # - mariadb:/bitnami/mariadb
      - mssql:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: Opensourc3!
      SA_PASSWORD: Opensourc3
    restart: always
    networks:
      default:
        ipv4_address: 172.16.1.212

volumes:
  mariadb:
    driver: 'local'
  redis:
    driver: 'local'
  postgres:
    driver: 'local'
  mssql:
    driver: 'local'

networks:
  default:
    external:
      name: picobug
